version: '3.8'

services:
  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5442:5430"

  books-db:
    image: postgres:15
    environment:
      POSTGRES_DB: books_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5443:5430"

  borrowing-db:
    image: postgres:15
    environment:
      POSTGRES_DB: borrowing_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5444:5430"

